"""initial schema

Revision ID: 380e05cd7254
Revises:
Create Date: 2026-04-23 13:36:37.654155

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "380e05cd7254"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profil_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("chemin_yaml", sa.Text(), nullable=False),
        sa.Column("contenu", sa.JSON(), nullable=True),
        sa.Column(
            "cree_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modifie_le", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nom"),
    )
    op.create_table(
        "source_externe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("type_api", sa.String(length=20), nullable=False),
        sa.Column("url_base", sa.Text(), nullable=False),
        sa.Column("ttl_cache_heures", sa.Integer(), nullable=False),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "utilisateur",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.Column(
            "cree_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nom"),
    )
    op.create_table(
        "vocabulaire",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uri_base", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cote_collection", sa.String(length=50), nullable=False),
        sa.Column("titre", sa.String(length=500), nullable=False),
        sa.Column("titre_secondaire", sa.Text(), nullable=True),
        sa.Column("editeur", sa.String(length=300), nullable=True),
        sa.Column("lieu_edition", sa.String(length=200), nullable=True),
        sa.Column("periodicite", sa.String(length=100), nullable=True),
        sa.Column("date_debut", sa.String(length=50), nullable=True),
        sa.Column("date_fin", sa.String(length=50), nullable=True),
        sa.Column("issn", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadonnees", sa.JSON(), nullable=True),
        sa.Column("notes_internes", sa.Text(), nullable=True),
        sa.Column("profil_import_id", sa.Integer(), nullable=True),
        sa.Column(
            "cree_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cree_par_id", sa.Integer(), nullable=True),
        sa.Column("modifie_le", sa.DateTime(), nullable=True),
        sa.Column("modifie_par_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cree_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modifie_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profil_import_id"],
            ["profil_import.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cote_collection"),
    )
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.create_index("ix_collection_titre", ["titre"], unique=False)

    op.create_table(
        "ressource_externe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("identifiant_externe", sa.String(length=300), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=True),
        sa.Column("titre", sa.Text(), nullable=True),
        sa.Column("auteurs", sa.JSON(), nullable=True),
        sa.Column("date", sa.String(length=50), nullable=True),
        sa.Column("metadonnees_brutes", sa.JSON(), nullable=True),
        sa.Column("manifeste_iiif", sa.Text(), nullable=True),
        sa.Column(
            "recupere_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("statut", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_externe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "identifiant_externe", name="uq_ressource_source_ident"
        ),
    )
    op.create_table(
        "valeur_controlee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vocabulaire_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("libelle", sa.String(length=300), nullable=False),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("ordre", sa.Integer(), nullable=True),
        sa.Column("actif", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["valeur_controlee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vocabulaire_id"],
            ["vocabulaire.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vocabulaire_id", "code", name="uq_valeur_vocab_code"),
    )
    op.create_table(
        "champ_personnalise",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("cle", sa.String(length=80), nullable=False),
        sa.Column("libelle", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("obligatoire", sa.Boolean(), nullable=False),
        sa.Column("valeurs_controlees_id", sa.Integer(), nullable=True),
        sa.Column("ordre", sa.Integer(), nullable=False),
        sa.Column("aide", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["valeurs_controlees_id"],
            ["vocabulaire.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "cle", name="uq_champ_collection_cle"),
    )
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("cote", sa.String(length=100), nullable=False),
        sa.Column("numero", sa.String(length=50), nullable=True),
        sa.Column("numero_tri", sa.Integer(), nullable=True),
        sa.Column("titre", sa.Text(), nullable=True),
        sa.Column("date", sa.String(length=50), nullable=True),
        sa.Column("annee", sa.Integer(), nullable=True),
        sa.Column("type_coar", sa.String(length=200), nullable=True),
        sa.Column("langue", sa.String(length=10), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadonnees", sa.JSON(), nullable=True),
        sa.Column("etat_catalogage", sa.String(length=30), nullable=False),
        sa.Column("notes_internes", sa.Text(), nullable=True),
        sa.Column(
            "cree_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cree_par_id", sa.Integer(), nullable=True),
        sa.Column("modifie_le", sa.DateTime(), nullable=True),
        sa.Column("modifie_par_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "etat_catalogage IN ('brouillon', 'a_verifier', 'verifie', 'valide', 'a_corriger')",
            name="ck_item_etat_catalogage",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cree_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modifie_par_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "cote", name="uq_item_collection_cote"),
    )
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.create_index("ix_item_annee", ["annee"], unique=False)
        batch_op.create_index("ix_item_collection_id", ["collection_id"], unique=False)
        batch_op.create_index("ix_item_etat", ["etat_catalogage"], unique=False)

    op.create_table(
        "fichier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("racine", sa.String(length=100), nullable=False),
        sa.Column("chemin_relatif", sa.Text(), nullable=False),
        sa.Column("nom_fichier", sa.String(length=500), nullable=False),
        sa.Column("hash_sha256", sa.String(length=64), nullable=True),
        sa.Column("taille_octets", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("largeur_px", sa.Integer(), nullable=True),
        sa.Column("hauteur_px", sa.Integer(), nullable=True),
        sa.Column("ordre", sa.Integer(), nullable=False),
        sa.Column("type_page", sa.String(length=30), nullable=False),
        sa.Column("folio", sa.String(length=20), nullable=True),
        sa.Column("etat", sa.String(length=20), nullable=False),
        sa.Column("derive_genere", sa.Boolean(), nullable=False),
        sa.Column("notes_techniques", sa.Text(), nullable=True),
        sa.Column(
            "ajoute_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ajoute_par_id", sa.Integer(), nullable=True),
        sa.Column("modifie_le", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ajoute_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "ordre", name="uq_fichier_item_ordre"),
        sa.UniqueConstraint("racine", "chemin_relatif", name="uq_fichier_chemin"),
    )
    with op.batch_alter_table("fichier", schema=None) as batch_op:
        batch_op.create_index("ix_fichier_etat", ["etat"], unique=False)
        batch_op.create_index("ix_fichier_hash", ["hash_sha256"], unique=False)
        batch_op.create_index("ix_fichier_item", ["item_id"], unique=False)
        batch_op.create_index("ix_fichier_nom", ["nom_fichier"], unique=False)

    op.create_table(
        "lien_externe_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("ressource_externe_id", sa.Integer(), nullable=False),
        sa.Column("type_relation", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "cree_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cree_par_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cree_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ressource_externe_id"],
            ["ressource_externe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id",
            "ressource_externe_id",
            "type_relation",
            name="uq_lien_item_ressource_type",
        ),
    )
    op.create_table(
        "modification_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("champ", sa.String(length=120), nullable=False),
        sa.Column("valeur_avant", sa.Text(), nullable=True),
        sa.Column("valeur_apres", sa.Text(), nullable=True),
        sa.Column(
            "modifie_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modifie_par_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modifie_par_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("modification_item", schema=None) as batch_op:
        batch_op.create_index("ix_mod_date", ["modifie_le"], unique=False)
        batch_op.create_index("ix_mod_item", ["item_id"], unique=False)

    op.create_table(
        "session_edition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column(
            "ouverte_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "dernier_heartbeat",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("fermee_le", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_fichier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("fichier_id", sa.Integer(), nullable=True),
        sa.Column("type_operation", sa.String(length=20), nullable=False),
        sa.Column("racine_avant", sa.String(length=100), nullable=True),
        sa.Column("chemin_avant", sa.Text(), nullable=True),
        sa.Column("racine_apres", sa.String(length=100), nullable=True),
        sa.Column("chemin_apres", sa.Text(), nullable=True),
        sa.Column("hash_avant", sa.String(length=64), nullable=True),
        sa.Column("hash_apres", sa.String(length=64), nullable=True),
        sa.Column("statut", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "execute_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("execute_par_id", sa.Integer(), nullable=True),
        sa.Column("annule_par_batch_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["execute_par_id"],
            ["utilisateur.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fichier_id"],
            ["fichier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operation_fichier", schema=None) as batch_op:
        batch_op.create_index("ix_op_batch", ["batch_id"], unique=False)
        batch_op.create_index("ix_op_date", ["execute_le"], unique=False)
        batch_op.create_index("ix_op_fichier", ["fichier_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operation_fichier", schema=None) as batch_op:
        batch_op.drop_index("ix_op_fichier")
        batch_op.drop_index("ix_op_date")
        batch_op.drop_index("ix_op_batch")

    op.drop_table("operation_fichier")
    op.drop_table("session_edition")
    with op.batch_alter_table("modification_item", schema=None) as batch_op:
        batch_op.drop_index("ix_mod_item")
        batch_op.drop_index("ix_mod_date")

    op.drop_table("modification_item")
    op.drop_table("lien_externe_item")
    with op.batch_alter_table("fichier", schema=None) as batch_op:
        batch_op.drop_index("ix_fichier_nom")
        batch_op.drop_index("ix_fichier_item")
        batch_op.drop_index("ix_fichier_hash")
        batch_op.drop_index("ix_fichier_etat")

    op.drop_table("fichier")
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index("ix_item_etat")
        batch_op.drop_index("ix_item_collection_id")
        batch_op.drop_index("ix_item_annee")

    op.drop_table("item")
    op.drop_table("champ_personnalise")
    op.drop_table("valeur_controlee")
    op.drop_table("ressource_externe")
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_index("ix_collection_titre")

    op.drop_table("collection")
    op.drop_table("vocabulaire")
    op.drop_table("utilisateur")
    op.drop_table("source_externe")
    op.drop_table("profil_import")
    # ### end Alembic commands ###
