"""ajout doi nakala

Revision ID: 619f10b212d5
Revises: 380e05cd7254
Create Date: 2026-04-23 14:57:37.761495

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "619f10b212d5"
down_revision: Union[str, None] = "380e05cd7254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doi_nakala", sa.Text(), nullable=True))
        batch_op.create_index("ix_collection_doi_nakala", ["doi_nakala"], unique=False)
        batch_op.create_unique_constraint("uq_collection_doi_nakala", ["doi_nakala"])

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doi_nakala", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("doi_collection_nakala", sa.Text(), nullable=True)
        )
        batch_op.create_index(
            "ix_item_doi_collection_nakala", ["doi_collection_nakala"], unique=False
        )
        batch_op.create_index("ix_item_doi_nakala", ["doi_nakala"], unique=False)
        batch_op.create_unique_constraint("uq_item_doi_nakala", ["doi_nakala"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_constraint("uq_item_doi_nakala", type_="unique")
        batch_op.drop_index("ix_item_doi_nakala")
        batch_op.drop_index("ix_item_doi_collection_nakala")
        batch_op.drop_column("doi_collection_nakala")
        batch_op.drop_column("doi_nakala")

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_constraint("uq_collection_doi_nakala", type_="unique")
        batch_op.drop_index("ix_collection_doi_nakala")
        batch_op.drop_column("doi_nakala")

    # ### end Alembic commands ###
