"""hierarchie collections

Revision ID: 6c56abe736b4
Revises: 619f10b212d5
Create Date: 2026-04-23 15:30:23.684320

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6c56abe736b4"
down_revision: Union[str, None] = "619f10b212d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_index("ix_collection_parent_id", ["parent_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_collection_parent_id", "collection", ["parent_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_constraint("fk_collection_parent_id", type_="foreignkey")
        batch_op.drop_index("ix_collection_parent_id")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
