"""table operation_import

Revision ID: 8c193feadcd0
Revises: 94ae179ad43c
Create Date: 2026-04-24 11:27:22.930304

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "8c193feadcd0"
down_revision: Union[str, None] = "94ae179ad43c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("profil_chemin", sa.Text(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("items_crees", sa.Integer(), nullable=False),
        sa.Column("items_mis_a_jour", sa.Integer(), nullable=False),
        sa.Column("items_inchanges", sa.Integer(), nullable=False),
        sa.Column("fichiers_ajoutes", sa.Integer(), nullable=False),
        sa.Column(
            "execute_le",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("execute_par", sa.Text(), nullable=True),
        sa.Column("rapport_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", name="uq_op_import_batch_id"),
    )
    with op.batch_alter_table("operation_import", schema=None) as batch_op:
        batch_op.create_index("ix_op_import_batch", ["batch_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operation_import", schema=None) as batch_op:
        batch_op.drop_index("ix_op_import_batch")

    op.drop_table("operation_import")
    # ### end Alembic commands ###
