"""descriptions internes et auteur principal

Revision ID: 94ae179ad43c
Revises: 1b5220a50dee
Create Date: 2026-04-24 10:06:52.798987

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "94ae179ad43c"
down_revision: Union[str, None] = "1b5220a50dee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("champ_personnalise", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description_interne", sa.Text(), nullable=True))

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description_interne", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("auteur_principal", sa.Text(), nullable=True))

    with op.batch_alter_table("valeur_controlee", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description_interne", sa.Text(), nullable=True))

    with op.batch_alter_table("vocabulaire", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description_interne", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vocabulaire", schema=None) as batch_op:
        batch_op.drop_column("description_interne")

    with op.batch_alter_table("valeur_controlee", schema=None) as batch_op:
        batch_op.drop_column("description_interne")

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_column("auteur_principal")
        batch_op.drop_column("description_interne")

    with op.batch_alter_table("champ_personnalise", schema=None) as batch_op:
        batch_op.drop_column("description_interne")

    # ### end Alembic commands ###
